# Generated by Django 4.0.5 on 2023-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('estado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
